### ISSUE TITLE
群组管理-创建群组抛异常

### ISSUE THREAD

**Issue by slinzhang007** [WeBankFinTech/WeBASE-Node-Manager#230]
由于在新增前置节点的时候没有把chainid设置进去，数据库中tbfront的chainid为null，所以在saveDataOfGroup函数中获取到的chainid也为null，在调用saveGroup的时候，由于需要chainid的int类型的参数，而chainid的类型为Integer，导致调用的时候转换失败抛出异常。

**Comment by CodingCattwo** [comment]
在1.4.2中已修复此问题
